### ISSUE TITLE
Final project review_Roi Siegelman

### ISSUE THREAD

**Issue by roisiegelman** [MeirSylman/MyAssignments#3]
Hi Meir, I've added a link to my final project and will like to get your input. https://github.com/roisiegelman/NSD1-in-Breast-Cancer

@szabgab

**Comment by MeirSylman** [comment]
Hi Roi,
Your project looks very interesting and well exlpained.

Few comments:
-I think there is a typo in the second paragraph " classification6. Of the".
-I couldn't find the pytest test_data_processing.py file.
- When I try to run python data_analysis.py:
 line 4, in <module>
    from lifelines import KaplanMeierFitter
ModuleNotFoundError: No module named 'lifelines'

Thanks for sharing your work with me

**Comment by roisiegelman** [comment]
Hi Meir,
I've fixed the typo and uploaded the test_data_processing.py file.

regarding the error, did you install all the required packages?
o run this script, you need to have the following Python libraries installed:

pandas
matplotlib
numpy
lifelines
gseapy
You can install these libraries using pip:

pip install pandas matplotlib numpy lifelines gseapy
 I've tried to run and it worked.

maybe try to clone my repository:

git clone  https://github.com/roisiegelman/NSD1-in-Breast-Cancer
NSD1-in-Breast-Cancer

**Comment by MeirSylman** [comment]
You right, I skipped the packages installation.
Now I made it, but got this error for pytest test_data_analysis.py:

FAILED test_data_analysis.py::test_run_gsea - ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
FAILED test_data_analysis.py::test_plot_kaplan_meier - AttributeError: 'Legend' object has no attribute 'legendHandles'. Did you mean: 'legend_handles'?
============================================= 2 failed, 5 passed in 6.83s =============================================

**Comment by szabgab** [comment]
>  you need to have the following Python libraries installed:
> 
> pandas matplotlib numpy lifelines gseapy You can install these libraries using pip:

that should be `pip install -r requirements.txt`

**Comment by roisiegelman** [comment]
Hi Meir,
first of all thank you for all your input and attention, I've done some corrections and editing and hopefully this time everything will work fine

**Comment by MeirSylman** [comment]
Hi Roi,
It all works also for me but the last pytest test_data_analysis.py. I got
=============================================== short test summary info
===============================================
FAILED test_data_analysis.py::test_run_gsea - ImportError: Missing optional
dependency 'openpyxl'.  Use pip or conda to install openpyxl.
FAILED test_data_analysis.py::test_plot_kaplan_meier - AttributeError:
'Legend' object has no attribute 'legendHandles'. Did you mean:
'legend_handles'?
============================================ 2 failed, 4 passed in 18.48s
=============================================

‫בתאריך יום א׳, 30 ביוני 2024 ב-8:09 מאת ‪Roi Siegelman‬‏ <‪
***@***.***‬‏>:‬

**Comment by roisiegelman** [comment]
added 'openpyxl' to the requirments. Hopefilly the editing fixed the problems when you run it (when I run the tests it works fine)

**Comment by MeirSylman** [comment]
I am still getting 

=============================================== short test summary info ===============================================
FAILED test_data_analysis.py::test_plot_kaplan_meier - AttributeError: 'Legend' object has no attribute 'legendHandles'. Did you mean: 'legend_handles'?
============================================ 1 failed, 5 passed in 25.66s =============================================

In addition, maybe it would be beneficial to add the 'openpyxl'  also to the readme file at the description of the requirments.

**Comment by roisiegelman** [comment]
Hi, I updated the data_analysis.py and hopefully it also solved the test_data_analysis.py problems

**Comment by MeirSylman** [comment]
=============================================== short test summary info ===============================================
FAILED test_data_analysis.py::test_plot_kaplan_meier - AttributeError: 'Legend' object has no attribute 'legendHandles'. Did you mean: 'legend_handles'?
============================================ 1 failed, 5 passed in 49.23s =============================================

**Comment by roisiegelman** [comment]
did you update the packages?

 import os
os.system('pip install --upgrade pandas openpyxl matplotlib numpy lifelines gseapy')

it's part of data_analysis.py

**Comment by roisiegelman** [comment]
I updated the line of requirments: 'pip install --upgrade -r requirements.txt'

**Comment by MeirSylman** [comment]
Yes, each time I have deleted the old version and cloned the new one.

Now it worked for me!

One last comment, I think it is good to add 'python' to the example of the code running. I mean 'python data_processing.py' and 'python data_analysis.py' in place of just 'data_processing.py' and 'data_analysis.py'

In summary, your project looks very interesting! thank you for sharing me!

**Comment by roisiegelman** [comment]
thank you for your input, sorry for all the messages

**Comment by roisiegelman** [comment]
good luck to you also
